# fly.toml file generated for your-fly-app on 2022-08-25T17:37:31+01:00
app = "diffusion-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[build]
  dockerfile = ".dockerfile"